export { anthemData }

const anthemData = [
  [
    {
      id: '0',
      area: 'Европа',
      country: 'Великобритания',
      nameRussian: 'Боже, храни Короля/Королеву!',
      nameSelf: 'God Save the King/Queen',
      langAnthem: 'Английский',
      autorAnthem: 'Генри Кэри',
      composer: 'Генри Кэри',
      dateWrite: '1745',
      dateAccept: '1745',
      }, {
      id: '1',
      area: 'Европа',
      country: 'Германия',
      nameRussian: 'Национальный гимн Германии',
      nameSelf: 'Deutsche Nationalhymne',
      langAnthem: 'Немецкий',
      autorAnthem: 'Генрих Гоффманн фон Фаллерслебен',
      composer: 'Йозеф Гайдн',
      dateWrite: '1841',
      dateAccept: '1952',
      }, {
      id: '2',
      area: 'Европа',
      country: 'Франция',
      nameRussian: 'Марсельеза',
      nameSelf: 'La Marseillaise',
      langAnthem: 'Французский',
      autorAnthem: 'Клод Жозеф Руже де Лиль',
      composer: 'Клод Жозеф Руже де Лиль',
      dateWrite: '1792',
      dateAccept: '1795, 1879',
      }, {
      id: '3',
      area: 'Европа',
      country: 'Италия',
      nameRussian: 'Песнь Итальянцев',
      nameSelf: 'Il Canto degli Italiani',
      langAnthem: 'Итальянский',
      autorAnthem: 'Гоффредо Мамели',
      composer: 'Микеле Новаро',
      dateWrite: '1847',
      dateAccept: '1946',
      }, {
      id: '4',
      area: 'Европа',
      country: 'Швейцария',
      nameRussian: 'Швейцарский псалом',
      nameSelf: 'Schweizerpsalm / Cantique suisse / Salmo svizzero / Psalm svizzer',
      langAnthem: 'Итальянский, Немецкий, Французский, Романшский',
      autorAnthem: 'Леонард Видмер',
      composer: 'Альберих Цвиссиг',
      dateWrite: '1841',
      dateAccept: '1961',
      }, {
      id: '5',
      area: 'Европа',
      country: 'Польша',
      nameRussian: 'Мазурка Домбровского / Марш Домбровского',
      nameSelf: 'Mazurek Dąbrowskiego',
      langAnthem: 'Польский',
      autorAnthem: 'Юзеф Выбицкий',
      composer: 'Неизвестно',
      dateWrite: '1797',
      dateAccept: '1927',
      }, {
      id: '6',
      area: 'Европа',
      country: 'Испания',
      nameRussian: 'Марш гренадеров',
      nameSelf: 'La Marcha Real',
      langAnthem: 'Испанский',
      autorAnthem: 'Эдуардо Маркина, Хосе-Мария Пеман, Паулино Куберо',
      composer: '',
      dateWrite: '',
      dateAccept: '1770',
      }, {
      id: '7',
      area: 'Европа',
      country: 'Австрия',
      nameRussian: 'Страна гор, страна потоков',
      nameSelf: 'Land der Berge, Land am Strome',
      langAnthem: 'Немецкий',
      autorAnthem: 'Паула фон Прерадович',
      composer: 'Вольфганг Амадей Моцарт',
      dateWrite: '1947',
      dateAccept: '1947',
      }, {
      id: '8',
      area: 'Европа',
      country: 'Швеция',
      nameRussian: 'Ты древняя, Ты свободная',
      nameSelf: 'Du gamla, Du fria',
      langAnthem: 'Шведский',
      autorAnthem: 'Рихард Дюбек, Луис Аллен',
      composer: 'Народная музыка',
      dateWrite: '1844',
      dateAccept: '',
      }, {
      id: '9',
      area: 'Европа',
      country: 'Финляндия',
      nameRussian: 'Наш край',
      nameSelf: 'Maamme',
      langAnthem: 'Финский',
      autorAnthem: 'Йохан Людвиг Рунеберг',
      composer: 'Фредрик Пациус',
      dateWrite: '1848',
      dateAccept: '',
    }
  ],
  [
    {
      id: '0',
      area: 'Африка',
      country: 'Египет',
      nameRussian: 'Родина, Родина, Родина',
      nameSelf: 'بلادي بلادي بلادي',
      langAnthem: 'Арабский литературный',
      autorAnthem: 'Мухаммад Юнус Аль Кади',
      composer: 'Сайед Дарвиш',
      dateWrite: '1878',
      dateAccept: '1979',
    }, {
      id: '1',
      area: 'Африка',
      country: 'ЮАР',
      nameRussian: 'Боже, благослови Африку / Голос Южной Африки',
      nameSelf: 'Nkosi Sikelel iAfrika / Die Stem van Suid-Afrika',
      langAnthem: '',
      autorAnthem: 'Енох Сонтонга, Корнелис Якобус Лангенховен',
      composer: 'Енох Сонтонга, Мартинус Лоуренс де Вильерс',
      dateWrite: '1897',
      dateAccept: '1997',
    }, {
      id: '2',
      area: 'Африка',
      country: 'Эфиопия',
      nameRussian: 'Вперёд, дорогая мать Эфиопия',
      nameSelf: 'ወደፊት ገስግሺ ውድ እናት ኢትዮጵያ',
      langAnthem: 'Амхарский',
      autorAnthem: 'Дэрэджэ Мэлаку Мэнгэша',
      composer: 'Сэломон Луку Мытыку',
      dateWrite: '1957',
      dateAccept: '1992',
    }, {
      id: '3',
      area: 'Африка',
      country: 'Тунис',
      nameRussian: 'Защитники Отечества',
      nameSelf: 'حماة الحمى',
      langAnthem: 'Литературный арабский',
      autorAnthem: 'Мустафа Садик ар-Рафии, Абу-ль-Касим аш-Шабби',
      composer: 'Мухаммед Абд аль-Ваххаб',
      dateWrite: '1987',
      dateAccept: '1987',
    }, {
      id: '4',
      area: 'Африка',
      country: 'Сомали',
      nameRussian: 'Хвалите родину',
      nameSelf: 'Qolobaa Calankeed',
      langAnthem: 'Сомалийский',
      autorAnthem: 'Абдуллахи Карше',
      composer: 'Абдуллахи Карше',
      dateWrite: '1959',
      dateAccept: '2012',
    }, {
      id: '5',
      area: 'Африка',
      country: 'Нигер',
      nameRussian: 'Нигерцы',
      nameSelf: 'La Nigérienne',
      langAnthem: 'Французский',
      autorAnthem: 'Морис Альбер Тирье',
      composer: 'Робер Жаке, Николя Абель, Франсуа Фрионне',
      dateWrite: '1961',
      dateAccept: '1961',
    }, {
      id: '6',
      area: 'Африка',
      country: 'Сенегал',
      nameRussian: 'Сыграйте на своих кора, ударьте в балафоны / Красный лев',
      nameSelf: 'Pincez Tous vos Koras, Frappez les Balafons / Le Lion rouge',
      langAnthem: 'Французский',
      autorAnthem: 'Леопольд Седар Сенгор',
      composer: 'Эрбер Пеппер',
      dateWrite: '1960',
      dateAccept: '1960',
    }, {
      id: '7',
      area: 'Африка',
      country: 'Нигерия',
      nameRussian: 'Гимн Нигерии',
      nameSelf: 'Arise, O Compatriots',
      langAnthem: 'Английский',
      autorAnthem: 'Джон А. Илечукву, Эме Этим Акпан, Б. А. Огуннайке, Соту Омоигуи, П. О. Адерибиге',
      composer: 'Нигерийский оркестр полиции',
      dateWrite: '1978',
      dateAccept: '1978',
    }, {
      id: '8',
      area: 'Африка',
      country: 'Мадагаскар',
      nameRussian: 'О наша любимая родина',
      nameSelf: 'Ô Terre de nos ancêtres chérie',
      langAnthem: 'Малагасийский, Французский',
      autorAnthem: 'Пастер Рахадзасон',
      composer: '',
      dateWrite: '1958',
      dateAccept: '1958',
    }, {
      id: '9',
      area: 'Африка',
      country: 'Танзания',
      nameRussian: 'Боже, благослови Африку',
      nameSelf: 'Mungu ibariki Afrika',
      langAnthem: 'Суахили, Английский',
      autorAnthem: 'Енох Сонтонга',
      composer: 'Енох Сонтонга',
      dateWrite: '1897',
      dateAccept: '1964',
    }
  ],
  [
    {
      id: '0',
      area: 'С. и Ю. Америка',
      country: 'Соединённые Штаты Америки',
      nameRussian: 'Знамя, усыпанное звёздами',
      nameSelf: 'The Star-Spangled Banner',
      langAnthem: 'Английский',
      autorAnthem: 'Фрэнсис Скотт Ки',
      composer: 'Джон Стаффорд Смит',
      dateWrite: '1814',
      dateAccept: '1931',
    }, {
      id: '1',
      area: 'С. и Ю. Америка',
      country: 'Канада',
      nameRussian: 'О Канада',
      nameSelf: 'O Canada',
      langAnthem: 'Английский',
      autorAnthem: 'Адольф-Базиль Рутье, Роберт Стэнли Уир',
      composer: 'Каликса Лавалле',
      dateWrite: '1880',
      dateAccept: '1980',
    }, {
      id: '2',
      area: 'С. и Ю. Америка',
      country: 'Мексика',
      nameRussian: 'Государственный гимн Мексики',
      nameSelf: 'Himno Nacional Mexicano',
      langAnthem: 'Испанский',
      autorAnthem: 'Франсиско Гонсалес Боканегра',
      composer: 'Хайме Нуно',
      dateWrite: '1853',
      dateAccept: '1943',
    }, {
      id: '3',
      area: 'С. и Ю. Америка',
      country: 'Куба',
      nameRussian: 'Гимн Баямо',
      nameSelf: 'El Himno de Bayamo',
      langAnthem: 'Испанский',
      autorAnthem: 'Перучо Фигередо',
      composer: 'Перучо Фигередо / Антонио Родригес Феррер',
      dateWrite: '1868',
      dateAccept: '1902',
    }, {
      id: '4',
      area: 'С. и Ю. Америка',
      country: 'Бразилия',
      nameRussian: 'Национальный гимн Бразилии',
      nameSelf: 'Hino Nacional Brasileiro',
      langAnthem: 'Португальский',
      autorAnthem: 'Осорио Дуке Эстрада',
      composer: 'Франсиско Мануэл да Силва',
      dateWrite: '1832',
      dateAccept: '1890',
    }, {
      id: '5',
      area: 'С. и Ю. Америка',
      country: 'Аргентина',
      nameRussian: 'Национальный гимн Аргентины',
      nameSelf: 'Himno Nacional Argentino',
      langAnthem: 'Испанский',
      autorAnthem: 'Висенте Лопес и Планес',
      composer: 'Блас Парера',
      dateWrite: '1812',
      dateAccept: '1813',
    }, {
      id: '6',
      area: 'С. и Ю. Америка',
      country: 'Перу',
      nameRussian: 'Национальный марш Перу',
      nameSelf: 'Marcha Nacional del Perú',
      langAnthem: 'Испанский язык, Аймара',
      autorAnthem: 'Хосе де ла Торре Угарте-и-Аларкон',
      composer: 'Хосе Бернардо Альседо',
      dateWrite: '1821',
      dateAccept: '1822',
    }, {
      id: '7',
      area: 'С. и Ю. Америка',
      country: 'Чили',
      nameRussian: 'Национальная песня',
      nameSelf: 'Canción Nacional',
      langAnthem: 'Испанский',
      autorAnthem: 'Эусебио Лильо',
      composer: 'Рамон Карнисер',
      dateWrite: '1827',
      dateAccept: '1828',
    }, {
      id: '8',
      area: 'С. и Ю. Америка',
      country: 'Венесуэла',
      nameRussian: 'Слава смелому народу',
      nameSelf: 'Gloria al Bravo Pueblo',
      langAnthem: 'Испанский',
      autorAnthem: 'Висенте Салиас',
      composer: 'Хуан Хосе Ландаэта',
      dateWrite: '1810',
      dateAccept: '1881',
    }, {
      id: '9',
      area: 'С. и Ю. Америка',
      country: 'Колумбия',
      nameRussian: 'Национальный гимн республики Колумбия',
      nameSelf: 'Himno Nacional de la República de Colombia',
      langAnthem: 'Испанский',
      autorAnthem: 'Рафаэль Нуньес',
      composer: 'Оресте Синдичи',
      dateWrite: '1887',
      dateAccept: '1920',
    }
  ],
  [
    {
      id: '0',
      area: 'Азия',
      country: 'Китай',
      nameRussian: 'Марш добровольцев',
      nameSelf: '义勇军进行曲',
      langAnthem: 'Путунхуа',
      autorAnthem: 'Тянь Хань',
      composer: 'Не Эр',
      dateWrite: '1934',
      dateAccept: '1949',
      }, {
      id: '1',
      area: 'Азия',
      country: 'Индия',
      nameRussian: 'Душа народа',
      nameSelf: 'জন গণ মন',
      langAnthem: 'Хинди, Английский',
      autorAnthem: 'Рабиндранат Тагор',
      composer: 'Рабиндранат Тагор',
      dateWrite: '1911',
      dateAccept: '1950',
      }, {
      id: '2',
      area: 'Азия',
      country: 'Саудовская Аравия',
      nameRussian: 'Да здравствует Король!',
      nameSelf: 'عاش الملك',
      langAnthem: 'Арабский',
      autorAnthem: 'Ибрагим Хафаджи',
      composer: 'Абдул Рахман Аль-Хатееб',
      dateWrite: '1935',
      dateAccept: '1950, 1984',
      }, {
      id: '3',
      area: 'Азия',
      country: 'Иран',
      nameRussian: 'Национальный гимн Исламской Республики Иран',
      nameSelf: 'سرود ملی جمهوری اسلامی ایران',
      langAnthem: 'Персидский',
      autorAnthem: 'Сайед Багери',
      composer: 'Хасан Рияхи',
      dateWrite: '1990',
      dateAccept: '1990',
      }, {
      id: '4',
      area: 'Азия',
      country: 'Таиланд',
      nameRussian: 'Национальная песня',
      nameSelf: 'เพลงชาติ',
      langAnthem: 'Тайский',
      autorAnthem: 'Луанг Саранупраран',
      composer: 'Пхра Чендурийанг',
      dateWrite: '1932',
      dateAccept: '1934',
      }, {
      id: '5',
      area: 'Азия',
      country: 'Монголия',
      nameRussian: 'Государственный гимн Монголии',
      nameSelf: 'Монгол Улсын төрийн дуулал',
      langAnthem: 'Монгольский',
      autorAnthem: 'Цэндийн Дамдинсурэн',
      composer: 'Билэгийн Дамдинсурэн; Лувсанжамбын Мурдорж',
      dateWrite: '1961',
      dateAccept: '1961',
      }, {
      id: '6',
      area: 'Азия',
      country: 'Республика Корея',
      nameRussian: 'Патриотическая песня',
      nameSelf: '애국가 / 愛國歌',
      langAnthem: 'Корейский',
      autorAnthem: 'Неизвестен (возможно Юн Чхихо)',
      composer: 'Ан Иктхэ',
      dateWrite: '1936',
      dateAccept: '1948',
      }, {
      id: '7',
      area: 'Азия',
      country: 'Вьетнам',
      nameRussian: 'Марш наступающей армии',
      nameSelf: '進軍歌',
      langAnthem: 'Вьетнамский',
      autorAnthem: 'Ван Као',
      composer: 'Ван Као',
      dateWrite: '1944',
      dateAccept: '1945, 1976',
      }, {
      id: '8',
      area: 'Азия',
      country: 'Пакистан',
      nameRussian: 'Гимн Исламской Республики Пакистан',
      nameSelf: '',
      langAnthem: 'Урду, Английский',
      autorAnthem: 'Абу Аль-Асар Хафиз Джаландхари',
      composer: 'Ахмед Гулам Али Чагла',
      dateWrite: '1952',
      dateAccept: '1954',
      }, {
      id: '9',
      area: 'Азия',
      country: 'КНДР',
      nameRussian: 'Песнь о любви к Родине / Патриотическая песня',
      nameSelf: '애국가',
      langAnthem: 'Корейский',
      autorAnthem: 'Пак Се Ён',
      composer: 'Ким Вон Гюн',
      dateWrite: '1946',
      dateAccept: '1947',
      }
  ], 
  [
    {
      id: '0',
      area: 'Океания',
      country: 'Австралия',
      nameRussian: 'Развивайся, прекрасная Австралия',
      nameSelf: 'Advance Australia Fair',
      langAnthem: 'Австралийский английский',
      autorAnthem: 'Питер Доддс Маккормик',
      composer: 'Питер Доддс Маккормик',
      dateWrite: '1878',
      dateAccept: '1984',
      }, {
      id: '1',
      area: 'Океания',
      country: 'Новая Зеландия',
      nameRussian: 'Боже, защити Новую Зеландию',
      nameSelf: 'God Defend New Zealand',
      langAnthem: 'Маори, Английский, Новозеландский язык жестов',
      autorAnthem: 'Томас Брэкен',
      composer: 'Джон Джозеф Вудс',
      dateWrite: '1870',
      dateAccept: '1940, 1977',
      }, {
      id: '2',
      area: 'Океания',
      country: 'Индонезия',
      nameRussian: 'Великая Индонезия',
      nameSelf: 'Indonesia Raya',
      langAnthem: 'Индонезийский',
      autorAnthem: 'Ваге Рудольф Супратман',
      composer: 'Ваге Рудольф Супратман',
      dateWrite: '1924',
      dateAccept: '1945',
      }, {
      id: '3',
      area: 'Океания',
      country: 'Папуа — Новая Гвинея',
      nameRussian: 'Встаньте, о сыны!',
      nameSelf: 'O Arise, All You Sons',
      langAnthem: 'Ток-писин, Английский, Хири-моту',
      autorAnthem: 'Том Шаклейди',
      composer: 'Том Шаклейди',
      dateWrite: '1975',
      dateAccept: '1975',
      }, {
      id: '4',
      area: 'Океания',
      country: 'Острова Кука',
      nameRussian: 'Бог — это Истина',
      nameSelf: 'Te Atua mou e',
      langAnthem: 'Кукский язык, Английский, Пукапука',
      autorAnthem: 'Па Тепаэру Те Рито Арики Дэвис',
      composer: 'Сэр Томас Дэвис',
      dateWrite: '1982',
      dateAccept: '1982',
      }, {
      id: '5',
      area: 'Океания',
      country: 'Соломоновы острова',
      nameRussian: 'Боже, храни наши Соломоновы Острова',
      nameSelf: 'God Save Our Solomon Islands',
      langAnthem: 'Английский',
      autorAnthem: 'Панапаса Балекана, Матила Балекана',
      composer: 'Панапаса Балекана',
      dateWrite: '1978',
      dateAccept: '1978',
      }, {
      id: '6',
      area: 'Океания',
      country: 'Восточный Тимор',
      nameRussian: 'Отечество',
      nameSelf: 'Pátria',
      langAnthem: 'Тетум, Португальский',
      autorAnthem: 'Франсишку Боржа да Кошта',
      composer: 'Афонсу Редентор де Араужу',
      dateWrite: '1979',
      dateAccept: '2002',
      }, {
      id: '7',
      area: 'Океания',
      country: 'Кирибати',
      nameRussian: 'Встань, Кирибати',
      nameSelf: 'Teirake Kaini Kiribati',
      langAnthem: 'Кирибати, Английский',
      autorAnthem: 'Уриум Тамуэра Иотэба',
      composer: 'Уриум Тамуэра Иотэба',
      dateWrite: '1979',
      dateAccept: '1979',
      }, {
      id: '8',
      area: 'Океания',
      country: 'Фиджи',
      nameRussian: 'Боже, Благослови Фиджи',
      nameSelf: 'Meda Dau Doka',
      langAnthem: 'Фиджийский, Английский, Фиджийский хинди',
      autorAnthem: 'Майкл Френсис Александр Прескотт',
      composer: 'Чарльз Остин Майлс',
      dateWrite: '1970',
      dateAccept: '1970',
      }, {
      id: '9',
      area: 'Океания',
      country: 'Вануату',
      nameRussian: 'Мы, мы, мы',
      nameSelf: 'Yumi Yumi Yumi',
      langAnthem: 'Бислама, Французский, Английский',
      autorAnthem: 'Франсуа Винсент Эссав',
      composer: 'Франсуа Винсент Эссав',
      dateWrite: '1980',
      dateAccept: '1980',
      }
  ]
]
